### ISSUE TITLE
MM crashes

### ISSUE THREAD

**Issue by Rus3545** [mzxrules/MasterOcarina#1]
Hi.
This release: [link](https://hylianmodding.com/Thread-Atom-A-Disassembly-and-Overlay-Utility-for-Zelda64) for "mm J1, P0, P1, GCJ, GCU, GCP, DBG" don't working.
> Path updated! Re-run program to continue
Initializing task list:
Unhandled Exception: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: value
   at System.IO.MemoryStream.set_Position(Int64 value)
   at mzxrules.OcaLib.VFileTable.GetOverlayRecord(Int32 index, Type type) in C:\Users\mzxrules\Google Drive\Documents\Visual Studio 2013\Projects\Projects\MasterOcarina\OcaLib\source\Rom\VFileTable.cs:line 319
   at Atom.DisassemblyTask.CreateTaskList(Rom rom) in C:\Users\mzxrules\Google Drive\Documents\Visual Studio 2013\Projects\Projects\MasterOcarina\Atom\DisassemblyTask.cs:line 204
   at Atom.Atom.DisassembleRom(RomVersion ver, String path) in C:\Users\mzxrules\Google Drive\Documents\Visual Studio 2013\Projects\Projects\MasterOcarina\Atom\program.cs:line 260
   at Atom.Atom.Main(String[] a) in C:\Users\mzxrules\Google Drive\Documents\Visual Studio 2013\Projects\Projects\MasterOcarina\Atom\program.cs:line 100

Exemples bases: [link](https://www.sendspace.com/file/ransd9)
My spreadsheets "ods" for help, see and use "help" and "script": [link](https://www.sendspace.com/file/7rg0aq)
Thank you.

**Comment by Rus3545** [comment]
I saw that something had changed, tried to compile ...
I could not. (
I got to these errors:

>  FileAddress.cs(31,28): error CS1001
  FileAddress.cs(31,49): error CS1002
  FileAddress.cs(31,53): error CS1519
  FileAddress.cs(34,19): error CS1519
  FileAddress.cs(34,31): error CS1519
  FileAddress.cs(35,17): error CS1519
  FileAddress.cs(35,27): error CS1519
  FileAddress.cs(38,16): error CS1520
  FileAddress.cs(50,52): error CS1019
  FileAddress.cs(50,53): error CS1001
  FileAddress.cs(50,74): error CS1002
  FileAddress.cs(50,74): error CS0116
  FileAddress.cs(50,78): error CS1022
  FileAddress.cs(52,24): error CS1520
  FileAddress.cs(52,40): error CS1001
  FileAddress.cs(79,5): error CS1022
  FileAddress.cs(80,1): error CS1022
  Endian.cs(200,25): error CS1525
  Endian.cs(200,31): error CS1003
  Endian.cs(201,25): error CS1525
  Endian.cs(201,31): error CS1003
  Endian.cs(202,25): error CS1525
  Endian.cs(202,31): error CS1003
  Endian.cs(208,25): error CS1525
  Endian.cs(208,32): error CS1003
  Endian.cs(209,25): error CS1525
  Endian.cs(209,32): error CS1003
  Endian.cs(210,25): error CS1525
  Endian.cs(210,32): error CS1003
  Endian.cs(216,25): error CS1525
  Endian.cs(216,30): error CS1003
  Yaz.cs(55,29): error CS1525
  Yaz.cs(55,34): error CS0443
  Yaz.cs(55,36): error CS1003
  Yaz.cs(411,29): error CS1528
  Yaz.cs(411,29): error CS1003
  Yaz.cs(411,30): error CS1525
  Yaz.cs(411,35): error CS0443
  Yaz.cs(411,37): error CS1026
  Yaz.cs(411,37): error CS1003
  Yaz.cs(411,42): error CS1003
  Yaz.cs(411,42): error CS1002
  Yaz.cs(411,42): error CS1513
  Yaz0.cs(54,29): error CS1525
  Yaz0.cs(54,34): error CS0443
  Yaz0.cs(54,36): error CS1003
  Endian.cs(217,25): error CS1525
  Endian.cs(217,30): error CS1003
  Endian.cs(218,25): error CS1525
  Endian.cs(218,30): error CS1003
  Endian.cs(223,25): error CS1525
  Endian.cs(223,29): error CS1003
  Endian.cs(224,25): error CS1525
  Endian.cs(224,29): error CS1003
  Endian.cs(225,25): error CS1525
  Endian.cs(225,29): error CS1003
  N64Ptr.cs(104,52): error CS1026
  N64Ptr.cs(104,52): error CS1002
  N64Ptr.cs(104,57): error CS1002
  N64Ptr.cs(104,57): error CS1513
  N64Ptr.cs(105,45): error CS1002

Is it something wrong with me or is the code just raw yet? 
I used MS Build Tools 2015(14.0) + NDP472-DevPack or ndp48-devpack for Win7x64.

I saw Yaz.cs in the report. Therefore, I will add a little more information, it will come in handy.
The absolutely accurate Yaz algorithm for N64 implemented by **Zoinkity** for Python "Nintendo.py":[link](https://www.sendspace.com/file/60jndw)
It has been ported to C# **onepiecefreak3**, Little Endian option is just not needed: [link](https://github.com/IcySon55/Kuriimu/tree/master/src/Kontract/Compression)
The fastest algorithm implemented by **dnasdw** for C++: [link](https://github.com/dnasdw/3dstool/tree/master/src)
N64 and GC Yaz are slightly different in compression ratio and speed...

**Comment by mzxrules** [comment]
It's failing to compile because Helper uses .net standard 2.0 i believe. I don't think MS Build Tools 2015 supports the .net standard

**Comment by Rus3545** [comment]
Ok. 
MS Build Tools 2017(15.0) + dotnet-sdk-2.2.109-win-x64 + dancing with a tambourine (like: dotnet restore Atom\Atom.csproj; MSBuildSDKsPath e,t,c) and the compilation goes successful.
But "mm DBG" test still fails:
> Path updated! Re-run program to continue
Initializing task list:
Unhandled Exception: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: value
   at System.IO.MemoryStream.set_Position(Int64 value)
   at mzxrules.OcaLib.VFileTable.GetOverlayRecord(Int32 index, Type type) in e:\Ma
sterOcarina\OcaLib\Rom\VFileTable.cs:line 311
   at Atom.DisassemblyTask.CreateTaskList(Rom rom) in e:\MasterOcarina\Atom\Disass
emblyTask.cs:line 205
   at Atom.Atom.DisassembleRom(RomVersion ver, String path) in e:\MasterOcarina\At
om\program.cs:line 260
   at Atom.Atom.Main(String[] a) in e:\MasterOcarina\Atom\program.cs:line 100

Thanks again. I will follow the updates. Hopefully fixed someday...

**Comment by mzxrules** [comment]
Think i figured out the issue. TransitionTable_Start was undefined in Addresses.xml for a number of MM versions. You should be able to fix this without recompiling the program by editing the /data/Addresses.xml file and changing the node to this: 

`      <Identifier id="TransitionTable_Start">
        <Address reftype="absolute" domain="ROM">
          <Data ver="J0">C82CD0</Data>
          <Data ver="J1">C82FA0</Data>
          <Data ver="U0">C670F0</Data>
          <Data ver="P0">DAD390</Data>
          <Data ver="P1">DAD4B0</Data>
          <Data ver="GCJ">C6EA00</Data>
          <Data ver="GCU">C749F0</Data>
          <Data ver="GCP">DBA4B0</Data>
          <Data ver="DBG">DF0600</Data>
        </Address>
      </Identifier>`

**Comment by Rus3545** [comment]
I will immediately ask a question on the spectrum, so as not to cause problems. Suddenly, my mistake too, or is it all irrelevant ... After all, everything compiles ...
MS Build Tools 2017 (15.0) NDP472 ndp48 dotnet-sdk-2.2.109 Newtonsoft.Json 12.0.3-beta1 System.ValueTuple 4.5.0
`"e:\Sharp\MasterOcarina\Spectrum\Spectrum.csproj" (Build target) (1) ->
(CoreCompile target) -> 
  log\ReferenceLogger.cs(19,22): warning CS0660: 'ReferenceLogger<T>.Reference<U>' defines operator == or operator != but does not override Object.Equals(object o) [e:\Sharp\MasterOcarina\Spectrum\Spectrum.csproj]
  log\ReferenceLogger.cs(19,22): warning CS0661: 'ReferenceLogger<T>.Reference<U>' defines operator == or operator != but does not override Object.GetHashCode() [e:\Sharp\MasterOcarina\Spectrum\Spectrum.csproj]
  Commands.cs(2450,13): warning CS0162: Unreachable code detected [e:\Sharp\MasterOcarina\Spectrum\Spectrum.csproj]
  ramstruct\ThreadStructA.cs(180,20): warning CS0169: The field 'OSThreadContext.__OSfp.dValue' is never used [e:\Sharp\MasterOcarina\Spectrum\Spectrum.csproj]

    4 Warning(s)
    0 Error(s)`
